

# General information about the website

title: Valentine Gilbart
description: Bioinformatician in NGS

sass:
  sass_dir: _sass/
  style: compressed

# Exclude files and folders from the build
exclude:
  - Gemfile
  - Gemfile.lock


# Markdown and syntax highlight
markdown: kramdown