# General information about the website
theme: jekyll-theme-dinky
title: Valentine Gilbart
description: Bioinformatician in NGS

# Add dinky theme
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
