

# General information about the website

title: Valentine Gilbart
description: Bioinformatician in NGS

sass:
  sass_dir: _sass/
  style: compressed

# Exclude files and folders from the build
exclude:
  - Gemfile
  - Gemfile.lock


# Markdown and syntax highlight
markdown: kramdown

kramdown:
  input: GFM
  highlighter: rouge

# This can help you to set default permalink for a folder
defaults:
  - scope:
      path: "_posts" #_posts folder
    values:
      permalink: "posts/:categories/:year/:month/:title:output_ext"
